version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - spark-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "my-topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - spark-network

  spark-notebook:
    image: jupyter/all-spark-notebook:latest
    container_name: spark-notebook
    ports:
      - "4040:4040"
      - "8888:8888"
    environment:
      SPARK_NOTEBOOK_OPTS: "--packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.2"
    volumes:
      - ./notebooks:/opt/docker/notebooks
    networks:
      - spark-network
    depends_on:
      - kafka

  web-socket-server:
    build: web-socket
    container_name: web-socket-server
    ports:
      - "6789:6789"
    networks:
      - spark-network
    depends_on:
      - kafka

networks:
  spark-network:
    driver: bridge